### ISSUE TITLE
Class Preferences Issues b4 Adding class to Cart

### ISSUE THREAD

**Issue by abundang** [ucsc/AIS-Mobile#1]
On the screen after you add the discussion section but before you add to the cart, there is a screen that I want to make look better. I'm going to attach screen shots with comments 

Essentially, the preferences section on desktop is at the top of the page. Much of the info is not that important but some of it is pretty critical (permission code and prerequisites) and I'm worried people won't find it on mobile. 

I'm really trying to figure out how to make it clearer. So I'm thinking it might be good to: 
1. ? Put the Class Preferences expandable section at the top but default to closed. (But I wonder if this will look ok since the other section isn't' in an expandable section) 
2. Reorder the stuff in Class Preferences to highlight the important stuff. 
- wait list 
- permission nbr 
- grading 
- units 
- General Education 
- Enrollment Information 

THEN at the bottom 
The misc. class info like class abbreviation, status, component, session, career 

I want to either not display it at all OR tighten it up a lot - see image attached called "mobile - class prefs"

![mobile - class prefs 1](https://cloud.githubusercontent.com/assets/13139500/14474860/e278660c-00b3-11e6-8b46-a0536d83a8cc.png)

<img width="590" alt="desktop - class prefs" src="https://cloud.githubusercontent.com/assets/13139500/14474877/f0e3b07a-00b3-11e6-8594-24ab6087fbac.png">

**Comment by leslieg** [comment]
fixed
