### ISSUE TITLE
Loose formatting on "Add to Cart" page 

### ISSUE THREAD

**Issue by abundang** [ucsc/AIS-Mobile#10]
Go to enrollment cart 
Add a class e.g. 60585 
"Add to Cart" (only click 1 time) 
Click the "Continue" bar that comes up at the bottom 
Click cancel 
Gives warning 
Click cancel again 
It takes you back to the Add to cart page but now the formatting is all messed up 
Attaching image: screen loses formatting.png
![screen loses formatting](https://cloud.githubusercontent.com/assets/13139500/14475352/69b4c410-00b6-11e6-82f3-6dede5803ab7.PNG)

**Comment by leslieg** [comment]
This appears to be fixed.
