### ISSUE TITLE
show/hide on class schedule weekly calendar view 

### ISSUE THREAD

**Issue by abundang** [ucsc/AIS-Mobile#21]
I am not sure what the show/hide on the weekly calendar view does.. and when I click on it, nothing seems to happen.

![shoe](https://cloud.githubusercontent.com/assets/13139500/14688407/4d23a90a-06f7-11e6-8c4b-39248fc9073e.png)

**Comment by leslieg** [comment]
I think this zooms in so it just displays the time you have classes.  So if you only had classes between 10 a.m. and 3 p.m., your schedule would only show that time frame.
