### ISSUE TITLE
 Add to cart takes two clicks

### ISSUE THREAD

**Issue by abundang** [ucsc/AIS-Mobile#4]
1. "Add to Cart" button takes two clicks 
   To reproduce, 
2. click Enrollment shopping cart tile 
3. enter class number in entry box 
4. click "Add to Cart" button 
   Observation: page seems to refresh but doesn't do anything (desired: goes to discussion section page) 
- Again: click "Add to Cart" button 

Now it goes to discussion section page.

**Comment by leslieg** [comment]
fixed
